application: mlab-ns
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: mlabns/images

- url: /stylesheets
  static_dir: mlabns/stylesheets

- url: /favicon.ico
  static_files: mlabns/images/favicon.ico
  upload: mlabns/images/favicon.ico

- url: /(update|register|tools|geo|search).*
  script: main.app

- url: /admin.*
  script: main.app
  #login: required

- url: /.*
  script: main.app

builtins:
- remote_api: on
- appstats: on

libraries:
- name: pycrypto
  version: latest
- name: django
  version: "1.2"
