application: mlab-ns
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /images
  static_dir: mlabns/images

- url: /stylesheets
  static_dir: mlabns/stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /favicon.ico
  static_files: mlabns/images/favicon.ico
  upload: mlabns/images/favicon.ico

- url: /(update|register|tools|geo|query).*
  script: main.app

- url: /status.*
  script: main.app

- url: /admin.*
  script: main.app
  #login: required

- url: /map/.*
  script: main.app
  #login: required

###### Start log2bq #######
#
- url: /solution/level4
  script: solution.level4.app

- url: /static
  static_dir: shell/static

- url: /shell.*
  script: shell.shell.application
  login: admin

- url: /oauth2callback
  script: oauth2client/appengine.py
###### End log2bq #######

- url: /.*
  script: main.app

builtins:
- remote_api: on
- appstats: on

libraries:
- name: pycrypto
  version: latest

- name: django
  version: "1.2"

- name: webapp2
  version: 2.5.1

- name: jinja2
  version: 2.6

###### Start log2bq #######
includes:
- mapreduce/include.yaml
###### End log2bq #######
