application: mlab-ns
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /images
  static_dir: mlabns/images

- url: /stylesheets
  static_dir: mlabns/stylesheets

- url: /favicon.ico
  static_files: mlabns/images/favicon.ico
  upload: mlabns/images/favicon.ico

- url: /(admin|map).*
  script: main.app
  #login: required

- url: /oauth2callback
  script: oauth2client/appengine.py

- url: /.*
  script: main.app

# Kept separate as I would like it to be only accessed via this domain.
- url: /pings
  script: main.app

builtins:
- remote_api: on
- appstats: on

libraries:
- name: pycrypto
  version: latest

- name: django
  version: "1.2"

- name: webapp2
  version: 2.5.1

- name: jinja2
  version: 2.6

includes:
- mapreduce/include.yaml
